### ISSUE TITLE
Add support for hidden fields in Touch UI dialog templates

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/AEM-Code-Templates#7]
[Hidden fields](https://docs.adobe.com/docs/en/aem/6-1/ref/granite-ui/api/jcr_root/libs/granite/ui/components/foundation/form/hidden/index.html) are quite useful in AEM dialogs as they can [provide useful hints and additional parameters to the Sling POST Servlet](https://sling.apache.org/documentation/bundles/manipulating-content-the-slingpostservlet-servlets-post.html).

Please add support for generating a basic hidden field to the Touch UI templates.

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
