### ISSUE TITLE
Touch UI Image Template missing a property

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/AEM-Code-Templates#8]
When used, the `aem_image` Touch UI template generates the following code (example with properties already filled in):

    <nodeName
        jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/foundation/form/fileupload"
        autoStart="{Boolean}false"
        class="cq-droptarget"
        fieldLabel="Field Label"
        fileNameParameter="./nodeName/fileName"
        mimeTypes="[image]"
        multiple="{Boolean}false"
        name="./nodeName/file"
        title="Field Label"
        useHTML5="{Boolean}true" />

When uploaded to AEM, such a  field is greyed out by default and it cannot be used.

Adding an `uploadUrl` property seems to enable the input, as seen in the screenshot below:

![Field with and without the uploadUrl property](https://cloud.githubusercontent.com/assets/8336085/23163422/af76e176-f832-11e6-8bf9-d1a9a82f091f.png)

Perhaps the field should be added to the template? I'm not sure what the value should be. I had a look at `foundation/components/image` for reference and it uses `${suffix.path}`... which I assume is HTL code that's somehow executed later?

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
